# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('wikipedia', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('institution_type', models.CharField(blank=True, choices=[('UNIVERSITY', 'University'), ('UNIVERSITY DEPARTMENT', 'University Department'), ('RESEARCH INSTITUTE', 'Research Institute'), ('COMPANY', 'Company'), ('INTERNATIONAL ORGANISATION', 'International Organisation')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miniclerval.Institution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
