# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacolumn',
            name='units',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
