# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0002_auto_20180103_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='has_surface',
        ),
        migrations.RemoveField(
            model_name='material',
            name='initially_perfect',
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='electronic_stopping_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='has_surface',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='initially_perfect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='thermostat_stopping_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
