# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 15:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0003_auto_20180103_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdbrecord',
            name='input_filename',
            field=models.CharField(default='default-filename', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdbrecord',
            name='energy',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PKA energy /keV'),
        ),
    ]
