# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0004_auto_20180109_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdbrecord',
            old_name='thermostat_stopping_comment',
            new_name='thermostat_comment',
        ),
        migrations.AlterField(
            model_name='latticeparameters',
            name='a',
            field=models.FloatField(verbose_name=' a /Å'),
        ),
        migrations.AlterField(
            model_name='latticeparameters',
            name='alpha',
            field=models.FloatField(verbose_name=' α /deg'),
        ),
        migrations.AlterField(
            model_name='latticeparameters',
            name='b',
            field=models.FloatField(verbose_name=' b /Å'),
        ),
        migrations.AlterField(
            model_name='latticeparameters',
            name='beta',
            field=models.FloatField(verbose_name=' β /deg'),
        ),
        migrations.AlterField(
            model_name='latticeparameters',
            name='c',
            field=models.FloatField(verbose_name=' c /Å'),
        ),
        migrations.AlterField(
            model_name='latticeparameters',
            name='gamma',
            field=models.FloatField(verbose_name=' γ /deg'),
        ),
    ]
