# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0005_auto_20180112_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdbrecord',
            name='nheader',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of header rows'),
        ),
    ]
