# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 12:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0007_auto_20180118_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdbrecord',
            name='initial_temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial temperature /K'),
        ),
        migrations.AlterField(
            model_name='cdbrecord',
            name='interatomic_potential_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
