# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0008_auto_20180119_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdbrecord',
            old_name='filename',
            new_name='archive_name',
        ),
        migrations.AlterField(
            model_name='cdbrecord',
            name='input_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
