# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0009_auto_20180129_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdbrecord',
            name='nheader',
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
