# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 14:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0010_auto_20180222_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdbrecord',
            name='box_X',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Box X-length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='box_X_orientation',
            field=models.CharField(blank=True, max_length=15, verbose_name='Box X-orientation'),
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='box_Y',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Box Z-length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='box_Y_orientation',
            field=models.CharField(blank=True, max_length=15, verbose_name='Box Y-orientation'),
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='box_Z_orientation',
            field=models.CharField(blank=True, max_length=15, verbose_name='Box Z-orientation'),
        ),
    ]
