# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0011_auto_20180329_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdbrecord',
            name='box_Z',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Box Z-length'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdbrecord',
            name='box_Y',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Box Y-length'),
        ),
    ]
