# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 10:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0013_auto_20180926_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdbrecord',
            name='archive_filesize',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
