# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0014_cdbrecord_archive_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdbrecord',
            name='initial_configuration_filename',
            field=models.CharField(blank=True, help_text='If provided, the filename of the .xyz file giving the initial state of the material in the simulation', max_length=100),
        ),
        migrations.AlterField(
            model_name='cdbrecord',
            name='input_filename',
            field=models.CharField(blank=True, help_text='The input filename(s) (or filename pattern) for the MD simulation code; separate multiple filenames by whitespace', max_length=100),
        ),
    ]
