# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0001_initial'),
        ('cdbmeta', '0017_cdbrecord_nsim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, help_text='If provided, the filename or URL to a resource providing the interatomic potential(s) used in the simulation', max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refs.Ref')),
            ],
        ),
        migrations.AddField(
            model_name='cdbrecord',
            name='potential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdbmeta.Potential'),
        ),
    ]
