# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-24 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0018_auto_20191020_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdbrecord',
            name='interatomic_potential_comment',
        ),
        migrations.RemoveField(
            model_name='cdbrecord',
            name='interatomic_potential_filename',
        ),
    ]
