# Generated by Django 2.2.10 on 2020-04-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0019_auto_20191024_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='publication_doi',
        ),
    ]
