# Generated by Django 3.2.19 on 2023-09-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdbmeta', '0020_remove_attribution_publication_doi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdbrecord',
            name='additional_columns',
        ),
    ]
