# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 22:06
from __future__ import unicode_literals

import cdb.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdbdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychunkedupload',
            name='file',
            field=models.FileField(max_length=255, upload_to=cdb.settings.CHUNKED_UPLOAD_TO),
        ),
    ]
