# Generated by Django 2.2.10 on 2020-04-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
        ('cdbdata', '0002_auto_20180222_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='upload_id',
        ),
        migrations.RemoveField(
            model_name='mychunkedupload',
            name='user',
        ),
        migrations.AddField(
            model_name='mychunkedupload',
            name='chunkedupload_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chunked_upload.ChunkedUpload'),
            preserve_default=False,
        ),
    ]
